---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: farmers-app
  name: farmers-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: farmers-app
  template:
    metadata:
      labels:
        run: farmers-app
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do sleep 1000; done
        image: farmers-market:1.1.5
        imagePullPolicy: Never
        name: farmers-app
        env:
          - name: MONGODB_USERNAME
            value: "farmeruser1"
          - name: MONGODB_PASSWORD
            value: "farmeruser1"
          # - name: MONGODB_USERNAME
          #  valueFrom:
          #    secretKeyRef:
          #      name: mongosecret
          #      key: mongo.initdb.root.username
          # - name: MONGODB_PASSWORD
          #  valueFrom:
          #    secretKeyRef:
          #      name: mongosecret
          #      key: mongo.initdb.root.password
          # - name: MONGODB_DATABASE
          #   valueFrom:
          #     configMapKeyRef:
          #       name: farmers-app-config
          #       key: mongodb.database
          - name: MONGODB_HOST
            valueFrom:
              configMapKeyRef:
                name: farmers-app-config
                key: mongodb.host
          - name: MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: farmers-app-config
                key: mongodb.port