---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongodb
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      volumes:
        - name: mongodata-pv-storage
          persistentVolumeClaim:
            claimName: mongodata-pv-claim
      containers:
      - image: mongo
        name: mongodb
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: mongo.initdb.root.username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: mongo.initdb.root.password
          - name: MONGO_INITDB_DATABASE
            value: inventory
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/db"
            name: mongodata-pv-storage
